First Changes
jonathanmunamire/Code-Review pull request #1
Opened 2022-09-26 08:49 UTC by jonathanmunamire

This is my First pull Request for this project

2022-09-26 09:13 UTC, jonathanmunamire reviewed
#Required Changes :recycle: 

Your Css Should have more than the background color; it is important to add other Css commands to make your page display properly

2022-09-26 09:16 UTC, jonathanmunamire commented on index.html
> +          height="315"
These Codes should be added to the Css file. It is always important to put Html and Css codes in separated files

2022-09-26 09:18 UTC, jonathanmunamire commented on index.html
> +        </div>
Good use of Div tags; but the parent div should better use class properties, for a better use in Css

2022-09-26 10:30 UTC, levy002 requested changes
## Hello @jonathanmunamire    , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to phrase the comments politely, as suggestions instead of orders.
For example:
    ### _"I think it would be better to use semantic tags"_

- [ ] Kindly make sure to always includes an explanation, a "why", for each requested change. For example:

* This is a well-explained request: 
    ### _*Why don't you use an article tag for the .first-article element instead of a div, that would improve the HTML structure and make the page more accessible*_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 14:26 UTC, jonathanmunamire reviewed
Hello
Good Job so far! But there are still changes that may Need to be done

# REQUIRED CHANGES :recycle: 

Kindly make sure to have a Css page; that would be helpful to sharpen your page

2022-09-26 14:29 UTC, jonathanmunamire commented on index.html
> +          height="315"
Good Job for your Html structure! Why didn't you put these values in your style.css file; It would be better to use separated Html and Css files

2022-09-26 14:32 UTC, jonathanmunamire commented on index.html
> +        <div class="features">
Why don't you use class properties in your div tags; they would be very helpful in order to identify your div tags in your Css file

2022-09-26 16:08 UTC, codecaiine commented on index.html
> +          height="315"
- [ ] Good job, :clap:  to have applied what the previous reviewer asked. However, I noticed a bad use of WHY. What the reviewer meant by WHY is to give the reason **why** you are asking for changes or suggestions to showcase your tech knowledge, you can also check google and always be polite in your comment. Please fix it :smile: 
let me just give an example: Good job for your html structure ... **PLEASE** put these values ....  it would be better to use  ... **BECAUSE**  separating HTML, CSS and JS is necessary for readability and maintainability.

2022-09-26 16:10 UTC, codecaiine commented on index.html
> +        </div>
- [ ] Good job, :clap:  to have applied what the previous reviewer asked. However, I noticed a bad use of WHY. What the reviewer meant by WHY is to give the reason **why** you are asking for changes or suggestions to showcase your tech knowledge, you can also check google and always be polite in your comment. Please fix it :smile: 
You can check the example in my first comment above :arrow_up:

2022-09-26 16:11 UTC, codecaiine requested changes
Hi @jonathanmunamire , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good use of inline comments :heavy_check_mark: 
- Good use of github flow :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 19:18 UTC, jonathanmunamire reviewed
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jonathanmunamire , I'm @jonathanmunamire , your reviewer for this PR  :wave: 

Good job so far!
There are some issues but you're almost there

![a little more](https://user-images.githubusercontent.com/20554583/192241479-b6304cb0-f256-4c64-a258-4f5a40a1e960.gif) 

## Good Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:

## Changes Required ♻️

_Check the comments under the review._

## Optional suggestions
_I strongly recommend you take the comment into account as they can make your code better._
- [ ] Make sure that your Linters works well :heavy_check_mark:👨🏻‍💻

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-26 19:21 UTC, jonathanmunamire commented on index.html
> +          height="315"
Great job with your Html Structure . Kindly make sure you have these Values in your sparated Css page

2022-09-26 20:00 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jonathanmunamire , I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] you did a great job by adding the inline comments but make sure you add the descriptive summary for your review so that the student will directly know if it is the required change, optional change, or invalid pull request. Please Watch this [video with an example](https://www.loom.com/share/e847c46aa4814534b23b3a8e4dd60d6d) it will help you to know how to make a summary of your review  :grinning: :grinning: :grinning: 
 - [ ] [ OPTIONAL] kindly add emojis and gifs it makes your required changes more friendly 
## example of the good summary 
 
```
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jossi30, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-26 20:00 UTC, MaganaAsiati commented on index.html
> +          height="315"
- you did a great job by adding inline comments but it should be better to always include an explanation, a "why" and start with kindly or please because the student passe a lot of time to work on the project it is better to be kind with him so that he will not be frustrated, for each requested change so that the next time the student will not repeat the error. :grinning: :grinning: :grinning:

example : 
Kindly remove the CSS code in your HTML file. It is always recommended to use a separate file for your HTML and CSS best practices. please follow this [ link ](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) to learn more about the HTML & CSS best practices :grinning: :grinning: :grinning:

2022-09-26 20:00 UTC, MaganaAsiati commented on index.html
> +          height="315"
- you did a great job by adding inline comments but it should be better to always include an explanation, a "why" and start with kindly or please because the student passe a lot of time to work on the project it is better to be kind with him so that he will not be frustrated, for each requested change so that the next time the student will not repeat the error. :grinning: :grinning: :grinning:

example : 
Kindly remove the CSS code in your HTML file. It is always recommended to use a separate file for your HTML and CSS best practices. please follow this [ link ](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) to learn more about the HTML & CSS best practices :grinning: :grinning: :grinning:

2022-09-27 08:18 UTC, Qoosim approved these changes
#   *Status: Approved* :tada: :heavy_check_mark: 

Hi @jonathanmunamire, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**Kindly check the optional comment I left under the review please**_ :pray: 

## Highlights

 -   Good code review performed. :heavy_check_mark: 
 -   Correct use of inline comments. :heavy_check_mark: 
 -   Good use of polite comments. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] I would recommend you to always give your PR a close descriptive name and good summary. It would have been better, if this PR carried a title like. _**Code Review Trial**_ and you state the work you've done in the PR under the summary. Well done for pushing it this far. You've done pretty well. All the best in your subsequent projects. :+1:

2022-09-27 14:49 UTC, merged